<!--<div class="container">-->
<!--    <div class="jumbotron">-->
<!--        <h1>Welcome!</h1>-->
<!--        <div class="form-group col-lg-6">-->
<!--            <a href="users/login/index" class="btn-sm btn-primary ">Sign In</a>-->
<!--            <a href="users/register/index" class="btn-sm btn-primary ">Sign Up </a>-->
<!--        </div>-->
<!--    </div>-->
<!---->
<!--</div>-->
<head>
    <link rel="stylesheet" href="css/myOwn.css" type="text/css">
</head>

<div class="carousel fade-carousel slide" data-ride="carousel" data-interval="4000" id="bs-carousel">
    <!-- Overlay -->
    <div class="overlay"></div>



    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item slides active">
            <div class="slide-1"></div>
            <div class="hero">
                <hgroup>
                    <h1>Welcome!</h1>
                    <h3>Get start with our survey application!</h3>
                </hgroup>
                <a href="users/login/index" class="btn btn-hero btn-lg">Sign In</a>
                <a href="users/register/index" class="btn btn-hero btn-lg">Sign Up </a>
            </div>
        </div>


    </div>
</div>
