<script>

    function checkedBox(val) {
        if(document.getElementById(val).checked)
        {
            //debugger;
            localStorage.setItem(val, val);
        }
        else
        {
            localStorage.removeItem(val);
        }


        //  document.getElementById("test1").innerHTML = localStorage.length;
    }
</script>
<table class="table">

    <?php foreach ($this->paginator as $question) :  ?>
        <tr>
            <td><?= $this->escapeHtml($question->text); ?></td>
        <?php foreach ($this->answers as $answer) :  ?>
            <tr>
                <?php if ($answer->idquestion == $question->idquestion) : ?>
                    <td>

                        <?php if ($answer->type == 'text') : ?> 
                            <input type="text" id="<?= $answer->idanswer ?>" >
                        <?php endif; ?>
                        <?php if ($answer->type == 'checkbox') : ?>
                            <input type="checkbox" id="<?= $answer->idanswer ?>" onchange="checkedBox(this.id)" >
                        <?php endif; ?>
                        <?php if ($answer->type == 'radio') : ?>
                            <input type="radio" id="<?= $answer->idanswer ?>">
                        <?php endif; ?>
                        <script>
                            if(localStorage.getItem(<?= $answer->idanswer ?>))
                            {
                                document.getElementById(<?= $answer->idanswer ?>).checked = true;
                            }
                            else
                            {
                                document.getElementById(<?= $answer->idanswer ?>).checked = false;
                            }

                        </script>
                        <?= $this->escapeHtml($answer->text); ?>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        </tr>

    <?php endforeach; ?>
</table>

<?= $this->paginationControl(
// the paginator object
    $this->paginator,
    // the scrolling style
    'sliding',
    // the partial to use to render the control
    ['users/partial/paginator.phtml', 'Users'],
    // the route to link to when a user clicks a control link
    [
        'route' => 'fill'
    ]
);
?>


<a href="<?= $this->url('survey', array('action'=>'index'));?>" class="btn btn-primary">Back</a>
