<?php
// module/Album/view/album/album/add.phtml:

$title = 'Create new survey';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL, ['controller'=>'survey', 'action' => 'create']));
/*$form->setAttribute('action', $this->url('survey', array('action' => 'create')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idsurvey'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('description'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

*/
?>

<?=$this->form()->openTag($form)?>
    <fieldset>
        <legend>Creating Survey</legend>

        <div class="control-group">
            <label class="control-label"><?=$this->formLabel($form->get('title'))?></label>
            <div class="controls">
                <?=$this->formElement($form->get('title'))?>
                <?=$this->formElementErrors($form->get('title'))?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label"><?=$this->formLabel($form->get('description'));?></label>
            <div class="controls">
                <?=$this->formElement($form->get('description'))?>
                <?=$this->formElementErrors($form->get('description'))?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label"><?=$this->formLabel($form->get('date'));?></label>
            <div class="controls">
                <?=$this->formElement($form->get('date'))?>
                <?=$this->formElementErrors($form->get('date'))?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label"><?=$this->formLabel($form->get('status'));?></label>
            <div class="controls">
                <?=$this->formElement($form->get('status'))?>
                <?=$this->formElementErrors($form->get('status'))?>
            </div>
        </div>


        <div class="control-group">
            <label class="control-label"></label>
            <div class="controls">
                <?=$this->formElement($form->get('submit'))?>
                <?=$this->formElementErrors($form->get('submit'))?>
            </div>
        </div>

    </fieldset>
<?=$this->form()->closeTag()?>