<?php
$title = 'My albums';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('survey', ['action' => 'create']) ?>">Create new Survey</a>
</p>
<table class="table">
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($albums as $album) : ?>
        <tr>
            <td><?= $this->escapeHtml($survey->title) ?></td>
            <td><?= $this->escapeHtml($survey->description) ?></td>
            <td>
                <a href="<?= $this->url('survey', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
                <a href="<?= $this->url('survey', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a>
                <a href="<?= $this->url('survey', ['action' => 'share', 'id' => $album->id]) ?>">Share</a>
                <a href="<?= $this->url('survey', ['action' => 'fill', 'id' => $album->id]) ?>">Fill out</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
