<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit survey';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'survey',
    array(
        'action' => 'edit',
        'idsurvey'     => $this->idsurvey,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idsurvey'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('description'));
echo $this->formhidden($form->get('date'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();