<?php
// module/Album/view/album/album/add.phtml:
use Zend\Session\Container; //dodane

$title = 'Create new survey';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('survey', array('action' => 'create')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idsurvey'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('description'));
echo $this->formhidden($form->get('date'));

$session = new Container('creation');

?>


<div class="controls">
    <label class="control-label"><?php echo $session->offsetGet('nquestion')."/". $session->offsetGet('AllQ').".",$this->formLabel($form->get('text'))?>:</label>
    <?=$this->formElement($form->get('text'))?>
    <?= $this->formElement($form->get('submitq')) ?>

    <?php
    if($session->offsetGet('nquestion')>1) {
        ?>
        <?= $this->formElement($form->get('submitpq')) ?>
        <?php
    }
    ?>
    <?php
    if($session->offsetGet('nquestion')<($session->offsetGet('AllQ'))){
        ?>
        <?= $this->formElement($form->get('submitnq')) ?>
        <?php
    }
    ?>
    <?=$this->formElementErrors($form->get('text'))?>
</div>
    <?php
    for($i=1; $i<=$session->offsetGet('nanswer');$i++) {
    ?>
<div class="controls">
    <label class="control-label"><?= $this->formLabel($form->get('text'.$i)) ?>:</label>
    <?= $this->formElement($form->get("text".$i)) ?>
    <label class="control-label"><?= $this->formLabel($form->get("type" . $i)) ?>:</label>
    <?= $this->formElement($form->get("type" . $i)) ?>
    <?= $this->formElement($form->get('submitda'.$i)) ?>
    <?=$this->formElementErrors($form->get('text'.$i))?>
    <?php
    }
    ?>



</div>

<div class="control-group">
    <label class="control-label"></label>
    <div class="controls">
        <?= $this->formElement($form->get('submita')) ?>
        <?= $this->formElement($form->get('submitdq')) ?>
        <?=$this->formElement($form->get('submit'))?>
    </div>
</div>
<?php
echo $this->form()->closeTag();
?>

<a href="<?php echo $this->url('survey', array('action'=>'logout'));?>" class="btn-primary btn">Logout</a>

<a href="<?php echo $this->url('survey',
    array('action'=>'delete', 'idsurvey' => $session->offsetGet('idsurvey')));?>" class="btn-primary btn">Delete</a>
<a href="<?php echo $this->url('survey', array('action'=>'index'));?>" class="btn btn-primary">Back</a>