<?php
// module/Album/view/album/album/add.phtml:

$title = 'Create new survey';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('survey', array('action' => 'create')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idsurvey'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('description'));
echo $this->formhidden($form->get('date'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

<a href="<?php echo $this->url('survey', array('action'=>'logout'));?>">Logout</a>
<br>
<a href="<?php echo $this->url('survey', array('action'=>'index'));?>">Back</a>