<?php
// module/Album/view/album/album/index.phtml:


$title = 'My Surveys';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('survey', array('action'=>'create'));?>">Create new Survey</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($surveys as $survey) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($survey->title);?></td>
            <td><?php echo $this->escapeHtml($survey->description);?></td>
            <td>
                <a href="<?php
                echo $this->url('survey',
                    array('action'=>'edit', 'idsurvey' => $survey->idsurvey));?>" class="btn-primary btn">Edit</a>
                <a href="<?php echo $this->url('survey',
                    array('action'=>'delete', 'idsurvey' => $survey->idsurvey));?>" class="btn-primary btn">Delete</a>
                <a href="<?php echo $this->url('fill',
                    array('action'=>'index', 'idsurvey' => $survey->idsurvey));?>" class="btn-primary btn">Fill</a>
                <a href="<?php echo $this->url('result',
                    array('action'=>'index', 'idsurvey' => $survey->idsurvey));?>" class="btn-primary btn">Result</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<a href="<?php echo $this->url('survey', array('action'=>'logout'));?>" class="btn-primary btn">Logout</a>