<script>
    function clearStorage() {
        var results = [];
        for (var i = 0; i < localStorage.length; i++){
            results[i] = localStorage.key(i);
        }
        for (var i = 0; i < localStorage.length; i++){
            localStorage.removeItem(localStorage.key(i));
        }


        $.ajax({
            type: "POST",
            url: "localhost/fill/save",
            data: {data: JSON.stringify(results)},
            dataType: 'json',
            success: function(data) {
                alert(JSON.stringify(data, null, 4));
            },
            error: function() {
                alert("failure");
            }
        });
    }

</script>
<?php if ($this->pageCount): ?>
    <div>
        <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>">
                        <<
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <<
                    </a>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>">
                        >>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        >>
                    </a>
                </li>
                <a href="<?php echo $this->url('survey', array('action'=>'index'));?>" class="btn btn-primary" onclick="clearStorage()">Complete Survey</a>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>