<script>
    function clearStorage() {

        var results = new Array(localStorage.length);
        for (var i = 0; i < localStorage.length; i++) {
            results[i] = new Array(2);
        }
        var key
        debugger;
        results[0][0] = localStorage.getItem('id');
        localStorage.removeItem('id');

        for (var i = 0; i < localStorage.length; i++){

            key = localStorage.key(i);
            if(isNaN(parseInt(localStorage.getItem(key))))
            {
                results[i+1][0] = key;
                results[i+1][1] = localStorage.getItem(key);
            }
            else
            {
                results[i+1][0] = localStorage.getItem(key);
            }

        }

        localStorage.clear()



        $.ajax({
            type: "POST",
            url: "/fill/save",
            data: {data: JSON.stringify(results)},
            dataType: 'json',
            success: function(data) {
                alert(JSON.stringify(data, null, 4));
            },

        });
    }

</script>
<?php if ($this->pageCount): ?>
    <div>
        <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>">
                        <<
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <<
                    </a>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>">
                        >>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        >>
                    </a>
                </li>
                <a href="<?php echo $this->url('survey', array('action'=>'index'));?>" class="btn btn-primary" onclick="clearStorage()">Complete Survey</a>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>
