<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL, ['controller'=>'login', 'action' => 'process']));
?>

<div class="container">

    <?=$this->form()->openTag($form)?>
    <fieldset>
        <legend>Sign In </legend>

        <div class="control-group">
            <label class="control-label"><?=$this->formLabel($form->get('email'))?></label>
            <div class="controls">
                <?=$this->formElement($form->get('email'))?>
                <?=$this->formElementErrors($form->get('email'))?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label"><?=$this->formLabel($form->get('password'))?>:</label>
            <div class="controls">
                <?=$this->formElement($form->get('password'))?>
                <?=$this->formElementErrors($form->get('password'))?>
            </div>
        </div>



        <div class="control-group">
            <label class="control-label"></label>
            <div class="controls">
                <?=$this->formElement($form->get('submit'))?>
            </div>
        </div>
    </fieldset>
    <?=$this->form()->closeTag()?>


    <br />
    <a href="/public/users">Homepage</a>

</div>